name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version (major.minor.patch)'
        required: true
        type: string
      skip-branch-status-check:
        description: 'Skip CI status check.'
        default: false
        required: false
        type: boolean

permissions:
  actions: write
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - uses: actions/setup-node@v6
        with:
          node-version-file: .github/node-version.txt
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install argon2-cffi
      
      - run: ./release/release.py ${{ inputs.version }} ${{ inputs.skip-branch-status-check }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
